# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Deploy new version

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
    - name: Extract Java version from pom.xml
      id: get-version
      run: |
          VERSION=$(grep -oP '(?<=<java.version>).*?(?=</java.version>)' pom.xml | xargs)
          echo "POM_JAVA_VERSION=$VERSION" >> $GITHUB_ENV

    - uses: mwensveen-nl/github-action/deploy@main
      with:
        java-version: ${{ env.POM_JAVA_VERSION }}
        github-token: ${{ secrets.MAVEN_REPO_WRITE}} 
